apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: profile-mysql
  namespace: liveproject
  labels:
    app: profile
spec:
  selector:
    matchLabels:
      app: profile
      tier: mysql
  template:
    metadata:
      labels:
        app: profile
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlroot
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysqluser
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqluser
              key: password
        - name: MYSQL_DATABASE
          value: "profiles"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
