apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sleep
  namespace: liveproject
  labels:
    app: sleep
spec:
  selector:
    matchLabels:
      app: sleep
      tier: service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sleep
        tier: service
    spec:
      containers:
      - image: grafpoo/sleep-app
        name: sleep
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://profile-mysql:3306/profiles
        - name: SPRING_DATASOURCE_USERNAME
          value: empuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/sleep
          initialDelaySeconds: 5
          periodSeconds: 5
