apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: profile
  namespace: liveproject
  labels:
    app: profile
spec:
  selector:
    matchLabels:
      app: profile
      tier: service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: profile
        tier: service
    spec:
      containers:
      - image: grafpoo/profile-app
        name: profile
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://profile-mysql:3306/profiles
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        ports:
        - containerPort: 8080
          name: profile
        volumeMounts:
        - name: profile-persistent-storage
          mountPath: /home
      volumes:
      - name: profile-persistent-storage
        persistentVolumeClaim:
          claimName: profile-pv-claim
