management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: mappings

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profiles
    username: empuser
    password: password
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true


logging:
  level:
    root: info

